os: linux
sudo: required
dist: trusty
language: c

compiler:
  - clang

branches:
  only:
    - coverity

before_install:
  - sudo apt-get install -y zlib1g-dev
  - sudo apt-get install -y libssl-dev
  - wget https://red.libssh.org/attachments/download/121/libssh-0.6.5.tar.xz
  - tar -xJf libssh-0.6.5.tar.xz
  - mkdir libssh-0.6.5/build && cd libssh-0.6.5/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..

  - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
  - tar -xJf cmocka-1.0.1.tar.xz
  - mkdir cmocka-1.0.1/build && cd cmocka-1.0.1/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..

  - git clone https://github.com/CESNET/libyang.git
  - mkdir libyang/build && cd libyang/build
  - git checkout devel
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..

  - echo $COVERITY_SCAN_PROJECT_NAME
  - echo $COVERITY_SCAN_TOKEN
  - echo $SCAN_URL

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "mNZta3ZKomYx+CMOLPfkPG3Sk8/AwIlcqHOtB/1mbIhCYpocDxDb3s6IhvcPcGpK+1T4fHNFQJogfkQL1VNO5Ox5g3Jol8JsTD2eD6gKU6ohuhqQRzFRoNgZclQJDtb2yXxtLltaC3UsMKxMxCI+Siyr8Hs4ZDA4AYoADDW60O6Sh6TFDcYbMhQYT+ln6ythIemW4nWPCitOr1yZH5QT1YZFW5qp7ycNpE/+tQ2P+PkL50gjzKnKaVrI8vFpRnOk2UUzl37fL/NafGdGslM+0f5cV7FAyL5dhlH7yljg3o8+5Xi/4JBzQxC423uKlmoTKpv9Uh37pm8f9Gh4I3cJTv1APW22ZevXgGC7BRG1nI5E6Y4vPT4MDvufucwz+kl5/mshM/4SgiWdpILf58bzts3XTrDQcfw8ByH3hJa9+2BW7edGPL6jg/6Dpvwz9nNFe6GtbVh45+X2iFp90moyLjEwf3I8gVKq7wl/Fk8ncbjtGLZB7sRTvTFyClF6B9ttiyfYukdF4CVfeTZVvVEFXBBN8iei5rtKcq6KShabOiqkcTcEgmsNC9LBtc/ZbsT4YU1HpKiYOhvnFfQB+T8/fjSUpcG621uzy+OHwbZ2HwZnQ+uOJLBEFyDFQApwFKlFknYdAVGkkEbq6Na2qZ3QOfp1cYGdISC5wA9ewgbUIXc="

addons:
  coverity_scan:
    project:
      name: "CESNET/libnetconf2"
    notification_email: rkrejci@cesnet.cz
    build_command_prepend: "mkdir build ; cd build ; cmake -DENABLE_TLS=ON -DENABLE_SSH=ON .. "
    build_command: "make"
    branch_pattern: coverity

script: 
  - echo "Coverity build done."

